app:
  image: legalbot:latest
  container_name: legalbot
  ports:
    - 7171:7171
    - 7172:7172
  volumes:
    - /tmp/legalbot/logs:/tmp/legalbot/logs
  links:
    - master
    - redis
    - mongodb

master:
  image: gettyimages/spark:2.3.0-hadoop-2.8
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  container_name: spark-master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  volumes:
    - ./conf/master:/conf
    - ./data:/tmp/data

worker:
  image: gettyimages/spark:2.3.0-hadoop-2.8
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  container_name: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  volumes:
    - ./conf/worker:/conf
    - ./data:/tmp/data
redis:
  image: redis:alpine
  command: redis-server --appendonly yes
  container_name: redis

mongodb:
  image: mongo:3.7
  container_name: mongodb
